"""`python -m ol.rollup` — regenerate status/ROLLUP.md from the git log.

The status is read off the card tags in commit subjects, never typed
(agent-runbook.md §9). Last status per card wins.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

CARD_RE = re.compile(r"^\[(?P<card>[A-Za-z0-9][A-Za-z0-9.\-/]*)\]\s+(?P<status>.+)$")
BUDGET_RE = re.compile(r"^budget:\s*(?P<budget>.+)$", re.IGNORECASE)


def git_log(repo: Path | None = None) -> tuple[list[str], dict[str, str]]:
    """Return (subjects oldest-first, card -> last budget line seen)."""
    result = subprocess.run(
        ["git", "log", "--reverse", "--format=%s%n%b%x00"],
        cwd=repo,
        capture_output=True,
        text=True,
        check=True,
    )
    subjects: list[str] = []
    budgets: dict[str, str] = {}
    for chunk in result.stdout.split("\x00"):
        lines = [line for line in chunk.splitlines() if line.strip()]
        if not lines:
            continue
        subject = lines[0]
        subjects.append(subject)
        match = CARD_RE.match(subject)
        if not match:
            continue
        for line in lines[1:]:
            budget = BUDGET_RE.match(line.strip())
            if budget:
                budgets[match["card"]] = budget["budget"].strip()
    return subjects, budgets


def statuses_from_log(subjects: list[str], budgets: dict[str, str]) -> dict[str, str]:
    del budgets
    statuses: dict[str, str] = {}
    for subject in subjects:
        match = CARD_RE.match(subject)
        if match:
            statuses[match["card"]] = match["status"].strip()
    return statuses


def render(statuses: dict[str, str], budgets: dict[str, str]) -> str:
    lines = ["# ROLLUP", "", "Generated by `python -m ol.rollup`. Do not edit.", ""]
    for card in sorted(statuses):
        lines.append(f"- [{card}] {statuses[card]}")
        if card in budgets:
            lines.append(f"  - budget: {budgets[card]}")
    lines.append("")
    lines.append(f"cards: {len(statuses)}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ol.rollup")
    parser.add_argument("--out", type=Path, default=Path("status") / "ROLLUP.md")
    parser.add_argument("--repo", type=Path, default=None)
    args = parser.parse_args(argv)

    subjects, budgets = git_log(args.repo)
    statuses = statuses_from_log(subjects, budgets)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(statuses, budgets))
    return 0


if __name__ == "__main__":
    sys.exit(main())
